import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "./Layout.module.css";
import Brightness6Icon from '@mui/icons-material/Brightness6';

const Layout = ({ children, title = "World Stats" }) => {
  const [theme, setTheme] = useState("light");

  const switchTheme = () => {
    if (theme === "light") {
      setTheme("dark");
      document.documentElement.setAttribute("data-theme", "dark");
    } else {
      setTheme("light");
      document.documentElement.setAttribute("data-theme", "light");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Link passHref href="/">
          <img
            src="https://i.imgur.com/Y28l856.png"
            alt="World Stats logo"
            width="150px"
          />
        </Link>
        <button className={styles.themeSwitcher} onClick={switchTheme}>
          <Brightness6Icon />
        </button>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>Pedro Lerida Nieto 2022</footer>
    </div>
  );
};

export default Layout;